---
title: "Untitled"
output: html_document
---

Packages.

```{r}

# check that the relative path works boys. 
setwd("~/HCI/week1")
pacman::p_load(tidyverse, lmerTest, corrplot)

```

Load data. 

```{r}

#Set your WD here:
df <- read.csv("clean_data.csv") %>%
  as_tibble() %>%
  glimpse()

df <- df %>%
  mutate(website = as_factor(website),
         event = as_factor(event),
         name = as_factor(name),
         order_tickets_online = as_factor(order_tickets_online),
         session = as_factor(session),
         cinemaxx_1st = as_factor(cinemaxx_1st)) %>%
  glimpse()

```

Correlation?

```{r}

# subset 
df_cor <- df %>%
  mutate(website_num = if_else(website == "cinemaxx", 0, 1)) %>% 
  select(!c(name, age, order_tickets_online,
            website, event, session, cinemaxx_1st)) %>%
  glimpse()

# correlation plot 
M <- cor(df_cor)
corrplot(M, method = "square", type = "upper")

```

preprocessing for summary data?

```{r}

# preprocessing 
df1 <- df %>%
  mutate(event_re = forcats::fct_recode(event, 
                               "0" = "fixation", 
                               "1" = "saccade"),
         event_num = as.numeric(event_re) - 1) %>%
  group_by(session, website, name) %>%
  mutate(n = row_number())


# more preprocessing 
df2 <- df1 %>%
  group_by(name, website,
           grouping = with(rle(event_num) %>% set_names(c("lengths2", "values")),
                        rep(seq_along(lengths2), lengths2))) %>%
  summarize(length = (max(n) - min(n) + 1),
            type = max(event_num))


# last step 
df3 <- df2 %>%
  pivot_wider(names_from = type, 
               values_from = length) %>%
  rename("fixation" = "0", 
         "saccade" = "1")

# more data wrangling needed. 
fixation <- df3 %>%
  filter(!is.na(fixation)) %>%
  select(!saccade)

saccade <- df3 %>%
  filter(!is.na(saccade)) %>%
  mutate(grouping = grouping - 1) %>%
  select(!fixation)

complete <- merge(fixation, saccade) %>%
  mutate(website_num = as.numeric(forcats::fct_recode(
    website, 
    "0" = "cinemaxx",
    "1" = "nfbio")) - 1) %>%
  glimpse()

# summary 
d <- complete %>%
  group_by(name, website_num) %>%
  summarize(dur_fix_total = sum(fixation),
            dur_sac_total = sum(saccade),
            dur_total_frq = dur_fix_total/(dur_fix_total + dur_sac_total),
            dur_fix_mean = mean(fixation),
            dur_sac_mean = mean(saccade),
            dur_mean_frq = dur_fix_mean/(dur_fix_mean+dur_sac_mean),
            n_events = n()) %>%
  glimpse()

```

models and plots.
here just numeric outcome. 
should be pretty much the same as categorical. 

```{r}

# models with summary: 
### number of fixations: 
m_events <- lm(website_num ~ n_events, 
               data = d)
summary(m_events)

### fixation duration: 
m_meanDur <- lm(website_num ~ dur_fix_mean + dur_sac_mean, 
               data = d)

summary(m_meanDur)

### fixation/saccade: 
m_frq <- lm(website_num ~ dur_total_frq, 
            data = d)
summary(m_frq)

```

Mouse-tracking (velocity)

```{r}

# scaling function (z)
scale_this <- function(x){
  (x - mean(x, na.rm=TRUE)) / sd(x, na.rm=TRUE)
}

# mouse velocity 
mouse <- df %>%
  mutate(lag_x = lag(mouse_x), 
         lag_y = lag(mouse_y)) %>%
  filter(!is.na(lag_x), !is.na(lag_y)) %>%
  mutate(vel_x = abs(mouse_x - lag_x),
         vel_y = abs(mouse_y - lag_y),
         mouse_vel = sqrt(vel_x^2 + vel_y^2),
         mouse_scaled = scale_this(mouse_vel),
         eye_scaled = scale_this(velocity)) %>%
  glimpse()

# plot mouse velocity 
mouse %>%
  ggplot() +
  geom_density(aes(x = mouse_vel)) 

# with logistic
velocity_log <- glmer(website ~ mouse_scaled + eye_scaled + (1|name),
                      family = binomial, data = mouse)

summary(velocity_log) # more cinemaxx for both mouse and eye velocity.

```

conclusion: ??

but! 
#2d DENSITY PLOT!

```{r}
fix = ggplot(df %>% filter(event == "fixation"), aes(x, y, color = website)) +
  geom_point(alpha = 0.01) +
  geom_density2d() + 
  labs(title = "Fixations")

mouse = ggplot(df, aes(mouse_x, mouse_y, color = website)) +
  geom_point(alpha = 0.01) +
  geom_density2d() +
  labs(title = "Mouse position")

p_load(cowplot)

plot_grid(fix, mouse, nrow = 2)
```

